## mysql image version
## ref: https://hub.docker.com/r/library/mysql/tags/
##
mysqlImage: mysql:5.7.13
# TODO(hoatle): use teracy/xtrabackup:2.4 by default instead
xtraBackupImage: gcr.io/google-samples/xtrabackup:1.0
imagePullPolicy: IfNotPresent

mysqlha:
  replicaCount: 3

  ## Password for MySQL root user
  ##
  # mysqlRootPassword: ## Default: random 10 character string

  ## Username/password for MySQL replication user
  ##
  mysqlReplicationUser: repl
  # mysqlReplicationPassword:

  ## Create a database user
  ##
  # mysqlUser:
  # mysqlPassword: ## Default: random 10 character string


  ## Allow unauthenticated access, uncomment to enable
  ##
  # mysqlAllowEmptyPassword: true

  ## Create database with name and grant all permissions to user on startup, if needed
  # mysqlDatabase:

  ## Configuration files for the master and slaves
  ##
  configFiles:
    master.cnf: |
      # Apply this config only on the master.
      [mysqld]
      log-bin
      skip_name_resolve
    slave.cnf: |
      # Apply this config only on slaves.
      [mysqld]
      super-read-only # only available >= 5.7.8
      # read-only # uncomment this when mysql < 5.7.8
      skip_name_resolve

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, azure-disk on
  ##   Azure, standard on GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessModes:
  - ReadWriteOnce
  size: 4Gi
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi

extraVolumes:

# restore data from a PV to /var/lib/mysql/
restore:
  enabled: false
  image: teracy/xtrabackup:2.4
  command: | # default command, should override this as you wish
    # FIXME(hoatle): restore the 2nd time did not work:
    # InnoDB: Log file ./ib_logfile1 is of different size 50331648 bytes than other log files 8388608 bytes!
    # InnoDB: Plugin initialization aborted with error Generic error
    # xtrabackup: innodb_init(): Error occured.
    set -ex
    xtrabackup --decompress
    xtrabackup --defaults-file=/xtrabackup_backupfiles/backup-my.cnf --prepare
    # make sure /var/lib/mysql is empty
    rm -rf /var/lib/mysql/* # dangerous here
    xtrabackup --copy-back
  extraVolumeMounts:

backup:
  enabled: false
  image: teracy/xtrabackup:2.4
  command: |
    set -ex
    echo "Waiting for mysqld to be ready (accepting connections)"
    until mysql -h 127.0.0.1 -e "SELECT 1"; do sleep 5; done
    rm -rf /xtrabackup_backupfiles/*
    xtrabackup --backup --compress --host=$MYSQL_HOST --user=$MYSQL_REPLICATION_USER --password=$MYSQL_REPLICATION_PASSWORD
    tail -f /dev/null # keep running
  extraVolumeMounts:

